const { Annotation, StateGraph } = require("@langchain/langgraph");
const { tool } = require("@langchain/core/tools");
const { ToolNode } = require("@langchain/langgraph/prebuilt");
const { ChatPromptTemplate, MessagesPlaceholder } = require("@langchain/core/prompts");
const { ChatOpenAI } = require("@langchain/openai");
const { z } = require("zod");
const { HumanMessage } = require("@langchain/core/messages");
const { logInfo, logError, ok, err } = require("../lib/commonfunc");
const { getPostsByUserId, addUserInterest } = require("../lib/fileAPI");

require("dotenv").config({ path: "../.env" });

/**
 * callInterestAgent
 *
 * 后台定期运行的“用户兴趣分析”代理：
 * - read_all_posts: 读取当前用户的所有帖子（文本 / 图片 / tag）
 * - write_user_interest: 将分析出的兴趣写入数据库
 *
 * 最终返回：[{ interest, relevant_score }, ...]，interest 为中文
 */
async function callInterestAgent(userId, thread_id) {
  console.log("[CALL_INTEREST_AGENT] start, userId:", userId);

  if (!userId) {
    throw new Error("callInterestAgent: userId is required.");
  }

  /** 1. 定义 Graph 状态 */
  const GraphState = Annotation.Root({
    messages: Annotation({
      reducer: (x, y) => x.concat(y),
      default: () => [],
    }),
  });

  /** 2. 工具：读取当前用户的所有帖子 */
  const readAllPostsTool = tool(
    async () => {
      logInfo("TOOL/read_all_posts", "called for userId:", userId);

      try {
        const posts = await getPostsByUserId(userId);

        if (!posts || posts.length === 0) {
          logInfo("TOOL/read_all_posts", "no posts found for userId:", userId);
          return JSON.stringify(
            err("NOT_FOUND", "No posts found for this user.", { userId })
          );
        }

        logInfo("TOOL/read_all_posts", "success, count:", posts.length);
        return JSON.stringify(
          ok({
            userId,
            posts,
          })
        );
      } catch (error) {
        logError("TOOL/read_all_posts", "exception:", error);
        return JSON.stringify(
          err("DB_ERROR", "read_all_posts failed.", {
            userId,
            detail: error?.message ?? String(error),
          })
        );
      }
    },
    {
      name: "read_all_posts",
      description:
        "Read ALL posts of the current user (including text, images, and existing tags). No arguments.",
      schema: z.object({}), // 无参数
    }
  );

  /** 3. 工具：写入用户兴趣 */
  const writeUserInterestTool = tool(
    async ({ interests }) => {
      logInfo(
        "TOOL/write_user_interest",
        "called for userId:",
        userId,
        "interests length:",
        interests?.length ?? 0
      );

      try {
        //   async function addUserInterest(userId, interestsArray) { ... }
        const resp = await addUserInterest(userId, interests);

        logInfo("TOOL/write_user_interest", "done for userId:", userId);

        return JSON.stringify(
          ok({
            userId,
            count: interests.length,
            result: resp ?? null,
          })
        );
      } catch (error) {
        logError("TOOL/write_user_interest", "exception:", error);
        return JSON.stringify(
          err("DB_ERROR", "write_user_interest failed.", {
            userId,
            detail: error?.message ?? String(error),
          })
        );
      }
    },
    {
      name: "write_user_interest",
      description:
        "Persist the analyzed interests for the bound user. It takes an array 'interests', where each element has 'interest' (Chinese string) and 'relevant_score' (0~1). Always use the current user_id.",
      schema: z.object({
        interests: z.array(
          z.object({
            interest: z.string(),
            relevant_score: z.number().min(0).max(1),
          })
        ),
      }),
    }
  );

  const tools = [readAllPostsTool, writeUserInterestTool];

  /** 4. ToolNode：根据 AIMessage.tool_calls 自动调工具 */
  const toolNode = new ToolNode(tools);

  /** 5. 初始化 LLM，并绑定工具 */
  const model = new ChatOpenAI({
    model: "doubao-seed-1-6-251015", // Ark 模型名
    temperature: 0.3, // 稍微降低，避免风格化，保证输出稳定
    configuration: {
      baseURL: "https://ark.cn-beijing.volces.com/api/v3",
      apiKey: process.env.ARK_API_KEY,
    },
  }).bindTools(tools);

  /** 6. agent 节点：组装 prompt + 调用 LLM */
  async function callModel(state) {
    console.log("[NODE/interest_agent] state messages length:", state.messages.length);

    const prompt = ChatPromptTemplate.fromMessages([
      [
        "system",
        `You are a user-interest analysis agent that ONLY works with two tools: read_all_posts and write_user_interest.

- There is exactly ONE bound user_id in this conversation. You must NEVER try to change it.
- read_all_posts: takes NO arguments, and returns ALL posts of this user.
  Each post may contain:
    - text content
    - image urls
    - tags (which are generated by another tagging agent)
- write_user_interest: takes ONLY one argument 'interests' (an array of objects),
  and ALWAYS writes interests for the current user_id.

Your job:
1. Use read_all_posts to fetch all posts.
2. Analyze the user's long-term interests based on:
   - post text content
   - image information (based on captions / descriptions if provided)
   - tags (highly important signals)

3. Produce an interests array in memory (do NOT output yet). Each element MUST have:
   {{
     "interest": string,            // 必须是简体中文的兴趣名称，例如 "二次元", "健身", "旅游-海边", "美食-日料"
     "relevant_score": number       // 0 ~ 1 之间的小数，越大表示兴趣越强
   }}

4. Language requirements:
   - 所有 "interest" 字段必须使用**简体中文**，不要用纯英文单词来充当兴趣名称。
   - 遇到专有名词（如 "NBA"、"iPhone"）可以保留英文，但整体兴趣短语仍然用中文描述，例如："NBA 篮球"、"苹果 iPhone 数码产品"。
   - 不要输出任何额外的中文解释、评论或句子，只输出 JSON 数组本身作为最终回答。

5. Other requirements for the interests array:
   - Summarize similar interests into a single more general interest if appropriate.
   - Provide 5~15 interests.
   - Sort the array by 'relevant_score' in DESCENDING order.
   - Make sure the JSON is valid and can be parsed by JSON.parse.

6. IMPORTANT workflow:
   - After you have constructed the final interests array in your reasoning, you MUST call tool "write_user_interest" exactly once, with the full interests array as argument.
   - When write_user_interest returns JSON (stringified):
     - If ok === true: then your FINAL assistant message must be EXACTLY the same interests array in pure JSON (no extra text).
     - If ok === false and error.code === "DB_ERROR": your FINAL assistant message must be an EMPTY JSON array [].
   - If read_all_posts returns error:
     - If error.code === "NOT_FOUND": your FINAL assistant message must be [].
     - If error.code === "DB_ERROR": your FINAL assistant message must be [].
   - After a "DB_ERROR" from any tool, do NOT call tools again with similar input.

Current time: {time}.`,
      ],
      new MessagesPlaceholder("messages"),
    ]);

    const formatted = await prompt.formatMessages({
      messages: state.messages,
      time: new Date().toISOString(),
    });

    console.log("[NODE/interest_agent] formatted messages count:", formatted.length);

    const aiMsg = await model.invoke(formatted);

    console.log(
      "[NODE/interest_agent] aiMsg finish_reason:",
      aiMsg.response_metadata?.finish_reason,
      "tool_calls:",
      aiMsg.tool_calls?.length || 0
    );

    return { messages: [aiMsg] };
  }

  /** 7. Router：如果有 tool_calls 就走 tools，否则结束 */
  function shouldContinue(state) {
    const msgs = state.messages;
    const last = msgs[msgs.length - 1];

    console.log(
      "[ROUTER_INTEREST] last message type:",
      last._getType?.() || typeof last,
      "tool_calls:",
      last.tool_calls?.length || 0
    );

    if (last.tool_calls?.length) {
      console.log("[ROUTER_INTEREST] -> tools");
      return "tools";
    }

    console.log("[ROUTER_INTEREST] -> __end__");
    return "__end__";
  }

  /** 8. 拼装 StateGraph */
  console.log("[CALL_INTEREST_AGENT] build workflow");
  const workflow = new StateGraph(GraphState)
    .addNode("agent", callModel)
    .addNode("tools", toolNode)
    .addEdge("__start__", "agent")
    .addConditionalEdges("agent", shouldContinue)
    .addEdge("tools", "agent");

  /** 9. 编译 graph */
  console.log("[CALL_INTEREST_AGENT] compile workflow");
  const app = workflow.compile();

  /** 10. 执行 workflow */
  console.log("[CALL_INTEREST_AGENT] invoke workflow");
  const finalState = await app.invoke(
    {
      messages: [
        new HumanMessage(
          `请基于当前用户${userId}的所有帖子（文本、图片、已有 tag），分析用户的长期兴趣，写入数据库后，再按说明输出 JSON 数组。`
        ),
      ],
    },
    {
      recursionLimit: 20,
      configurable: { thread_id },
    }
  );

  console.log(
    "[CALL_INTEREST_AGENT] finalState messages length:",
    finalState.messages.length
  );

  const outputMsg = finalState.messages[finalState.messages.length - 1];
  const output = outputMsg.content;

  console.log("[INTEREST_AGENT OUTPUT]", output);

  // output 应该是一个 JSON 字符串（或可直接 parse 的内容）
  try {
    if (typeof output === "string") {
      return JSON.parse(output);
    }
    return output;
  } catch (e) {
    logError("CALL_INTEREST_AGENT", "JSON parse error:", e);
    return [];
  }
}

module.exports = { callInterestAgent };
